### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by cocojoe**
Dependencies updated due to listed vulnerabilities

### CODE REVIEW

**Comment by JohnMcLear** [comment]
remove package-lock.json please!

**Comment by cocojoe** [comment]
I have not just added it, it's always been there. So why remove now?

Also https://docs.npmjs.com/files/package-lock.json 
`This file is intended to be committed into source repositories, and serves various purposes:`

**Comment by JohnMcLear** [comment]
My bad, I just saw it was +3000 lines of additional code but it appears that package-lock.json does that now..  NPM got bloated huh ;/

**Comment by JohnMcLear** [comment]
What's the relevent cve for the vulnerability?

**Pull request merged**
