### PR TITLE
Windows oauth integration

### PR DESCRIPTION
**Pull request by davidemerritt**
allow for the use of windows native applications along with a new publicly hosted cordova plugin (that we wrote).

@darkyen - thanks for the tip of the windowsAuthentication Broker.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Tested and not working.

Tested by:
* cloning plugin repository into app/node_modules
* Modifying app/node_modules/@auth0/cordova/src/index.js to match PR
* Build & Run in VS2017

In VS2017 error is
```
Unhandled exception at line 7, column 414839 in ms-appx-web://zz.yy.xx/www/js/auth0.js
0x800a138f - JavaScript runtime error: Unable to get property 'open' of undefined or null reference
```

Question..  Should I be updating/modifying www/js/auth0.js in my app or?  That file is minified/built down and I assume it's built from src/index.js so...??

**Comment by johnclarkemills** [comment]
@JohnMcLear @davidemerritt update this a while back and it is working for us.  Is there a timeline and when you guys will merge this?

**Comment by darkyen** [comment]
Hey David, 

Unfortunately, I do not have a windows phone / pc device to test this end to end, can you verify this that this still works (post the April updates). We are internally discussing if we want to support WP officially.

**Comment by davidemerritt** [comment]
@darkyen - have you guys come to any conclusion on support for windows mobile devices?

**Pull request closed without merging**
